#Steam Workshop Downloader Configuration
#Sat Nov 29 17:28:48 CET 2025
appId=431960
downloadPath=D\:\\Users\\Juan\\Downloads\\pruebasJarDownloader
lastWorkshopId=3590757351
steamCmdPath=D\:\\Users\\Juan\\Desktop\\\u00A0\\Halo 1 & Custom Edition\\Halo 1\\Halo ejecutar.eXe
useAnonymous=false
username=juanba50
